#!/usr/bin/env bash

# Use GNU ls instead of the BSD version on macOS
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias ls='gls -Fh --color=always'
else
    alias ls='ls -Fh --color=always'
fi

alias grep='grep --color=always'
alias fgrep='fgrep --color=always'
alias egrep='egrep --color=always'

alias ll='ls -la'

alias bc='bc -l -q ~/.config/bcrc'

alias hd='hexdump -C'

alias cd..='cd ..'

alias ncal='ncal -s ES -b'
alias epoch='date +%s'
alias iso8601='date -Iseconds'

alias scrsize='printf "%sx%s\n" $COLUMNS $LINES'

alias ydl='yt-dlp'

alias mp3dload='ydl -x --audio-format mp3'
alias oggdload='ydl -x --audio-format vorbis'

alias nethackx11='NETHACKOPTIONS="windowtype:x11" nethack'
alias nethackcurses='NETHACKOPTIONS="windowtype:curses" nethack'

alias direwolf='direwolf -c $HOME/.direwolf.conf'

alias rap='rsync -raP'

alias latexbuild='latexmk -pvc -pdf -view=none --shell-escape -pdflatex="pdflatex -interaction=nonstopmode -synctex=1" -outdir=build'

alias pubip='curl icanhazip.com'

alias clipboard='xclip -selection clipboard'

# vim: set syntax=sh:
