#!/usr/bin/env bash

alias grep="grep --color=always"
alias fgrep="fgrep --color=always"
alias egrep="egrep --color=always"

alias ll="ls -la"

alias bc="bc -l -q ~/.config/bcrc"

alias hd="hexdump -C"

alias cd..="cd .."

alias ncal="ncal -s ES -b"
alias epoch="date +%s"
alias iso8601="date -Iseconds"

alias scrsize="printf '%sx%s\n' $COLUMNS $LINES"

alias ydl="yt-dlp"

alias direwolf="direwolf -c $HOME/.direwolf.conf"

alias rap="rsync -raP"

alias latexbuild="latexmk -pvc -pdf -view=none --shell-escape -pdflatex='pdflatex -interaction=nonstopmode -synctex=1' -outdir=build"

alias pubip="curl icanhazip.com"

alias clipboard="xclip -selection clipboard"

alias ddown="docker compose down"
alias dup="docker compose up"
alias dupd="docker compose up -d"
alias ddup="docker compose down && docker compose up"

# vim: set syntax=sh:
