add_newline = false
command_timeout = 1000

[character]
success_symbol = "[>](bold green)"
vicmd_symbol = "[<](bold green)"
error_symbol = "[>](bold red)"

[package]
disabled = true

[line_break]
disabled = true

[time]
disabled = false
format = "@ [$time]($style) "
time_format = "%T"
utc_time_offset = "-4"
