" Behaviour
set cursorline
set autoindent
set autoread
set backspace=indent,eol,start
set clipboard=unnamed
set complete-=i
set completeopt+=noselect
set confirm
set expandtab
set hidden
set hlsearch
set incsearch
set mouse+=a
set nobackup
set nu
set ruler
set shiftwidth=4
set smartindent
set smarttab
set so=10
set softtabstop=4
set tabstop=4
set textwidth=80
set title
set wildmenu
set wrap
filetype plugin on
set relativenumber
