require('general')
require('plugins')
require('appearance')
require('keymaps')
require('syntax')
require('commands')

require('autocomplete')
require('copilot')
require('lsp')
require('telescope_conf')
require('neoterm')
require('treesitter')
require('autoformat')
require('texlab')
