return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "volar",
      "cmake",
      "tailwindcss",
      "zls",
      "texlab",
      "taplo",
      "rust_analyzer",
      "ruff_lsp",
      "lua_ls",
      "jsonls",
      "cssls",
      "html",
      "bashls",
      "clangd",
      "docker_compose_language_service",
      "dockerls",
      "emmet_ls",
      "ruff",
      "vtsls",
      "codelldb",
      "jsonlint",
      "cpplint",
    },
  },
}
