return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "clangd",
      "cmake-language-server",
      "codelldb",
      "cpplint",
      "css-lsp",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "emmet-ls",
      "html-lsp",
      "jsonlint",
      "json-lsp",
      "lua-language-server",
      "ruff",
      "rust-analyzer",
      "tailwindcss-language-server",
      "taplo",
      "texlab",
      "vtsls",
      "vue-language-server",
      "zls",
    },
  },
}
